name: WPScan Golden Image

on:
  push:
    branches:
      - main

jobs:
  build-sign-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build Docker Image
      run: |
        docker build --build-arg WPSCAN_API_TOKEN=${{ secrets.WPSCAN_API_TOKEN }} -t wpscan-appsec .

    - name: Run Docker Bench Security
      run: |
        docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v /usr/lib/systemd:/usr/lib/systemd docker/docker-bench-security

    - name: Install Cosign
      run: |
        wget https://github.com/sigstore/cosign/releases/latest/download/cosign-linux-amd64 -O cosign
        chmod +x cosign
        sudo mv cosign /usr/local/bin/cosign

    - name: Import Cosign Private Key
      env:
        COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
      run: |
        echo "$COSIGN_PRIVATE_KEY" > cosign.key
        chmod 600 cosign.key

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

    - name: Tag for AWS ECR
      run: |
        docker tag wpscan-appsec ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/wpscan-appsec:latest

    - name: Sign Docker Image with Cosign
      env:
        COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSPHRASE }}
      run: |
        cosign sign --key cosign.key ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/wpscan-appsec:latest

    - name: Push to AWS ECR
      run: |
        docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/wpscan-appsec:latest




